### ISSUE TITLE
Cannot read property 'StandardUsed' of undefined

### ISSUE THREAD

**Issue by phpbg** [jeanfabrice/livebox-exporter#1]
Hello,
j'ai l'erreur suivante durant la collecte:
```
TypeError: Cannot read property 'StandardUsed' of undefined
    at /usr/src/app/server.js:196:65
```

Je suppose que c'est parce que j'ai la fibre...?
Idéalement cette section pourrait être facultative...

**Comment by jeanfabrice** [comment]
Hello,

Je n'ai pas testé sur une Livebox fibre, n'en disposant pas, mais effectivement, la majorité - voire la totalité - des métriques remontées relèvent de la technologie ADSL et non de la fibre.

Je crains que cet exporter ne vous soit pas d'une grande utilité.

**Comment by phpbg** [comment]
j'ai essayé de trouver une autre mib que `dsl`.

A priori ce serait `eth` en fibre, cependant elle ne contient aucune statistique sur les paquets...

Dommage, merci pour quand même pour le projet!

**Comment by phpbg** [comment]
@jeanfabrice pour info, on peut collecter les statistiques réseau en UPnP. Il faut activer le service UPnP de la box, et utiliser cet exporter: https://github.com/yrro/igd-exporter/ (il y a quelques modifications à faire, tickets ouverts à ce sujet)
