### ISSUE TITLE
Est-ce qu'il y a possibilité d'avoir d'autres stats ?

### ISSUE THREAD

**Issue by fatpat** [jeanfabrice/livebox-exporter#2]
Bonjour,

je suis intéressé par le débit instantané in/ou de la box sur le wan voir, soyons fou, le débit in/ou sur le lan (par port ?) et le wlan.

Mais j'avoue avoir des doutes que la possibilité d'avoir ces informations.

**Comment by jeanfabrice** [comment]
Bonjour, 

malheureusement non, je n'ai pas creusé ce point et cette information ne semble pas disponible par le biais de l'interface que j'utilise.
Néanmoins, la Livebox disposant d'un service UPnP IGD, l'exporter Prometheus [igd-exporter](https://github.com/yrro/igd-exporter) pourrait convenir moyennant certaines adaptations (voir les issues ouvertes par @phpbg). Vous pourriez alors disposer des statistiques réseau, mais uniquement coté WAN il me semble.

**Comment by phpbg** [comment]
Bonjour,
oui, je vous confirme, statistiques WAN de la livebox disponibles via UPnP, en patchant à la main [igd-exporter](https://github.com/yrro/igd-exporter).
Pour le LAN et le WIFI je n'ai pas regardé.
Appliquer à la main les trois corrections:
* https://github.com/yrro/igd-exporter/issues/2
* https://github.com/yrro/igd-exporter/issues/3
* https://github.com/yrro/igd-exporter/issues/4

**Comment by fatpat** [comment]
j'ai forké le repo pour faire les modifs, vu que le code date d'il y a 4 ans j'ai des doutes sur le fait qu'il soit encore maintenu ;)

https://github.com/fatpat/igd-exporter
